### ISSUE TITLE
change style name for MapboxMap

### ISSUE THREAD

**Issue by kodermax** [MeilleursAgents/react-mapbox-wrapper#16] opened 2018-12-01 22:20 UTC
Please change name of field style for MapboxMap.
for example: mapStyle.
I can make PR.

**Comment by Heisendev** [comment] 2018-12-03 13:37
Hi! 
just to exactly know what the problem is, can you explain why do you want/need this change ? 

You're welcome to open a PR 😄  ( don't forget to follow the [pull_request_template.md](https://github.com/MeilleursAgents/react-mapbox-wrapper/blob/master/PULL_REQUEST_TEMPLATE.md) 😉 )

**Comment by kodermax** [comment] 2018-12-03 13:39
eslint rule react/style-prop-object
We use a reserved attribute.

**Comment by danousna** [comment] 2018-12-06 15:13
Closing this issue, the PR is merged and released in v2.0.0 https://github.com/MeilleursAgents/react-mapbox-wrapper/releases/latest

**Closed by danousna** 2018-12-06 15:13 UTC
